### ISSUE TITLE
Fail to Run - Distribution, Ping Pong and Seqlogo

### ISSUE THREAD

**Issue by mariferrarini** [SamuelHLewis/sRNAplot#1]
Dear author,

I am trying to use your tool but I've arrived at a problem I couldn't fix. When running 

`python sRNAplot.py -s sample -i file.bam --distribution`
`python sRNAplot.py -s sample -i file.bam --seqlogo`
`python sRNAplot.py -s sample -i file.bam --pingpong`

I get the following errors (respectively) :

```
Traceback (most recent call last):
  File "sRNAplot.py", line 833, in <module>
    fiveprime_host = bam_5prime_stranded(file=InFile,minlength=MinLength,maxlength=MaxLength,unique=Unique)
  File "sRNAplot.py", line 381, in bam_5prime_stranded
    count = int(linesplit[0].split('-')[1])
IndexError: list index out of range
```

```
Traceback (most recent call last):
  File "sRNAplot.py", line 822, in <module>
 bam_seqlogo(file=InFile,outfilename=Sample+'_'+InFile.strip('.bam'),minlength=MinLength,maxlength=MaxLength,unique=Unique)
  File "sRNAplot.py", line 700, in bam_seqlogo
    count = int(linesplit[0].split('-')[1])
IndexError: list index out of range
```

```
Traceback (most recent call last):
  File "sRNAplot.py", line 827, in <module>
overlap_plot(outname=Sample+'_'+InFile.strip('.bam')+'_PingPong.pdf',bamfile=InFile,minlength=MinLength,maxlength=MaxLength,minoverlap=1,maxoverlap=30)
  File "sRNAplot.py", line 809, in overlap_plot
    outfile = PdfPages(outname)
  File "/User/miniconda2/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py", line 2472, in __init__
    self._file = PdfFile(filename, metadata=metadata)
  File "/User/miniconda2/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py", line 438, in __init__
    fh, opened = cbook.to_filehandle(filename, "wb", return_opened=True)
  File "/User/miniconda2/lib/python2.7/site-packages/matplotlib/cbook/__init__.py", line 609, in to_filehandle
    fh = io.open(fname, flag, encoding=encoding)
IOError: [Errno 2] No such file or directory: file.bam_PingPong.pdf
```

They might be related to different issues, however, it seems that my problem might be a very basic error that's generating all of the other issues. Apparently running --unique seems to work fine.

Would you have any insights on how can I solve this?

Thank you very much,
Mariana.

**Comment by SamuelHLewis** [comment]
Hi!

The first two "list index out of range" errors, and the fact that adding the --unique option allows the script to run, suggest that it is not reading your bam file correctly. The script is designed to run on bam files produced by mapping collapsed reads, which in fasta format look like:

>1-7842671
CCGGGGCGGGCACCCTTGATCAAGAGTCGGTA
>2-756007
GCCGGGGCGGGCACCCTTGATCAAGAGTCGGTA

The script then looks through the bam file for the names, and extracts the read count by splitting the name string on the "-" and taking the second element of the resulting list. If you mapped uncollapsed reads, your reads won't be named in this format, so it will not be able to split the name on "-" and will throw the "list index out of range" error. However, if you run it with the --unique option it doesn't bother trying to split the names to find the read count for each read, but instead just sets all read counts to be 1.

If you didn't collapse your reads before mapping them, I would recommend collapsing them, remapping and running the commands again. If the problem still persists after this, let me know what the error message is and I'll be happy to help!

**Comment by mariferrarini** [comment]
Okay, got it! I'll try that and if it does not work, I'll come back with the issue.
Thank you very much!
