### ISSUE TITLE
When should we choose --unique?

### ISSUE THREAD

**Issue by xinl22** [SamuelHLewis/sRNAplot#2]
Hi Sam,

What's the significance of the option "--unique"? I know is's optional, but it seems that choosing it would lost some information if specific reads were enriched in some samples. I just don't understand the significance of deduplication here. So when should we choose --unique?

Thanks,
Xin

**Comment by SamuelHLewis** [comment]
Hi Xin,

The --unique option is included for situations where you want to stop the length distribution being dominated by highly-abundant small RNAs. For example, if you are looking for rare piRNAs, but your sample contains a few highly-expressed microRNAs, the 22nt peak might be so big that the piRNA peak at 25-30nt is obscured. In cases like this, running the program with and without the --unique option can provide a helpful insight into how much influence highly-abundant small RNAs are having.

Cheers!
