### ISSUE TITLE
No module named 'Bio'

### ISSUE THREAD

**Issue by brianpenghe** [SamuelHLewis/sRNAplot#3]
Do you know which "Bio" package I should install?

Traceback (most recent call last):
  File "sRNAplot.py", line 14, in <module>
    import Bio
ModuleNotFoundError: No module named 'Bio'

**Comment by SamuelHLewis** [comment]
This is the [biopython](https://biopython.org/) package

**Comment by brianpenghe** [comment]
Thanks
